### ISSUE TITLE
Question: What does this mean? 

### ISSUE THREAD

**Issue by mrjammock** [ItayLisaey/stick-around#18]
![Screenshot_20220220-202326~2.jpg](https://user-images.githubusercontent.com/95573703/154860430-4846525f-57ab-4f5f-94c4-326895c5f8f7.jpg)

What does "Have been confirmed by our moderators" mean?

**Comment by mrjammock** [comment]
Btw I changed my username ^^

**Comment by ItayLisaey** [comment]
Hey, for now it basically means I saw the movie and manually voted on it.
Also an opening for adding trusted moderators further down the line.

**Comment by mrjammock** [comment]
Ah okay thx :)
Since I watch a lot of movies, I am offering my help ^^
(just watched Uncharted 1 hour ago xD)

**Comment by ItayLisaey** [comment]
> Ah okay thx :)
> Since I watch a lot of movies, I am offering my help ^^
> (just watched Uncharted 1 hour ago xD) 

When I start working on it I'll tell you.
Thanks anyway!
