### ISSUE TITLE
"Should you wait"-tile not loading in Play Store Public Beta

### ISSUE THREAD

**Issue by mrjammock** [ItayLisaey/stick-around#3]
Hi, the should you wait tile doesn't load (although excellent internet connection).
I'm running A11 on OnePlus8T with the latest Public Beta Version of Stick Around.

(Btw I hope I'm doing this issue thing right, it's my first issue opened in github)

**Comment by ItayLisaey** [comment]
hey, as I wrote in the other issue you opened I'm currently working on the next version.
I already posted the new version to the public beta and it should be available anytime now

**Comment by mrjammock** [comment]
Hi, just got the new public beta (Update from Jan 9th, according to play store).
But the should you wait tile is still not loading tho:

![Screenshot_20220110-163956.jpg](https://user-images.githubusercontent.com/95573703/148793913-a5fb1cef-1cb3-4609-bf74-830cd7972c7f.jpg)

**Comment by ItayLisaey** [comment]
Hey I know, thanks for checking it out.
The debug APK works fine so I'm still trying to figure out what's the problem. 

I already uploaded a new version that will hopefully fix that issue.

Google Play review process usually takes me about a day so tomorrow I hope it will be available.

**Comment by ItayLisaey** [comment]
> Hey I know, thanks for checking it out.
> The debug APK works fine so I'm still trying to figure out what's the problem. 
> 
> I already uploaded a new version that will hopefully fix that issue.
> 
> Google Play review process usually takes me about a day so tomorrow I hope it will be available.

The new version number after the fix should be >1.1.2

**Comment by mrjammock** [comment]
okay thanks 👌

**Comment by mrjammock** [comment]
@ItayLisaey
Just got the 1.1.2, but the same problem is still present

**Comment by ItayLisaey** [comment]
> @ItayLisaey
> Just got the 1.1.2, but the same problem is still present

I know :(
I still don't know what's the problem.

**Comment by ItayLisaey** [comment]
> @ItayLisaey Just got the 1.1.2, but the same problem is still present

@anonymous-melon 
Update! I think if found out what's the problem!
There was an issue with the minification of the release apk (this is way I had problems debugging it).

I fixed it and posted a new release with version number 1.1.3, I hope that was the problem.
anyway Google Play review seem to take longer than usual in the last couple of days so I really can't estimate when it will be live.

**Comment by mrjammock** [comment]
I'll keep you updated whether it works then 👍

**Comment by mrjammock** [comment]
@ItayLisaey 
1.1.3 works flawless 👍

![Screenshot_20220112-074328.jpg](https://user-images.githubusercontent.com/95573703/149077340-cedf0484-623b-45d6-bfb8-387f43b3ec15.jpg)

![Screenshot_20220112-074309.jpg](https://user-images.githubusercontent.com/95573703/149077343-4bef6ccc-7fd5-4bc2-84d7-0a067dad394d.jpg)
