### ISSUE TITLE
Voting buttons not working

### ISSUE THREAD

**Issue by mrjammock** [ItayLisaey/stick-around#4]
Hi, the voting buttons are not working in Stable Version (Version 2.2 I think).
You're able to click on the vote button, but the the green thumbs-up and the red thumbs-down button can't be clicked.
I'm running A11 on OnePlus8T with Stable Play Store Version (Play Store says it's Version 2.2).

**Comment by ItayLisaey** [comment]
Hey, thank you for opening an issue.
Yes I know, the voting is currently purposely disabled for security reasons (the old server I wrote was pretty bad in terms of security).
planning on releasing a version in the next couple of days that integrates the new server.

**Comment by mrjammock** [comment]
Alright 👍

**Comment by mrjammock** [comment]
Btw great App, I love it!

**Comment by mrjammock** [comment]
This bug also got fixed in 1.1.3 👍
Imma close the issue
