### ISSUE TITLE
Suggestion: Use the "Releases" feature 

### ISSUE THREAD

**Issue by mrjammock** [ItayLisaey/stick-around#6]
I suggest using the "Releases" feature of GitHub.
It's basically an overview of the latest releases which can be found at the start page of the repository.
It you haven't come across this feature, here is an example:

https://github.com/KieronQuinn/TapTap

[The example is the repository of an app called Tap Tap, which enables the double-tap feature (known from pixel devices) on other Android devices.]

**Comment by ItayLisaey** [comment]
Will look into it. 
Thank you for being active and helpful 🙏

**Comment by ItayLisaey** [comment]
@anonymous-melon 
hey, just added the first release. 🥇

**Comment by mrjammock** [comment]
@ItayLisaey 👌

**Comment by mrjammock** [comment]
@ItayLisaey 
Additionally, it would be cool if you'd provide the APK via the "assets" -feature. 
Here's an example:

![Screenshot_20220112-122542.jpg](https://user-images.githubusercontent.com/95573703/149132043-38ba82e8-9a36-4cbc-82e2-f410aca31cec.jpg)
